<?xml version="1.0"?>
<package format="3">
  <name>drone_auto_bag_record</name>
  <version>0.1.0</version>
  <description>ROS 2 arming-triggered rosbag2 recorder for PX4/MAVROS flight tests.</description>

  <maintainer email="chanjoon.park@kaist.ac.kr">Chanjoon Park</maintainer>
  <author email="eungchang_mason@kaist.ac.kr">Eungchang Mason Lee</author>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>mavros_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>ros2bag</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>
  <exec_depend>rosbag2_storage_default_plugins</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
