drone_auto_bag_recorder:
  ros__parameters:
    output_dir: ~/bags/predictnav
    bag_prefix: qav250_position_vins
    state_topic: /mavros/state

    record_on_armed: true
    stop_on_disarm: true
    start_immediately: false
    include_state_topic: true

    record_all: false
    regex: ""
    exclude_regex: ""
    include_hidden_topics: false
    include_unpublished_topics: false
    no_discovery: false

    storage_id: sqlite3
    compression_mode: none
    compression_format: zstd
    max_cache_size: 268435456
    max_bag_size: 0
    max_bag_duration: 0
    log_level: info
    stop_timeout_s: 8.0

    topics:
      - /rosout
      - /parameter_events
      - /diagnostics
      - /tf
      - /tf_static
      - /mavros/state
      - /mavros/extended_state
      - /mavros/sys_status
      - /mavros/estimator_status
      - /mavros/status_event
      - /mavros/statustext/recv
      - /mavros/timesync_status
      - /mavros/time_reference
      - /mavros/battery
      - /mavros/vfr_hud
      - /mavros/rc/in
      - /mavros/rc/out
      - /mavros/imu/data
      - /mavros/imu/data_raw
      - /mavros/imu/mag
      - /mavros/altitude
      - /mavros/local_position/pose
      - /mavros/local_position/pose_cov
      - /mavros/local_position/odom
      - /mavros/local_position/velocity_body
      - /mavros/local_position/velocity_body_cov
      - /mavros/local_position/velocity_local
      - /mavros/odometry/out
      - /mavros/vision_pose/pose
      - /mavros/setpoint_position/local
      - /mavros/setpoint_raw/attitude
      - /mavros/setpoint_raw/target_attitude
      - /mavros/setpoint_raw/local
      - /mavros/setpoint_raw/target_local
      - /vins_estimator/odometry
      - /vins_estimator/path
      - /vins_estimator/imu_propagate
      - /vins_estimator/camera_pose
      - /vins_estimator/camera_pose_visual
      - /vins_estimator/extrinsic
      - /vins_estimator/point_cloud
      - /vins_restart
      - /vins_imu_switch
      - /vins_cam_switch
      - /camera/depth/image_rect_raw
      - /camera/depth/camera_info
      - /camera/depth/metadata
      - /camera/color/image_raw
      - /camera/color/image_rect_raw
      - /camera/color/camera_info
      - /camera/infra1/camera_info
      - /camera/infra2/camera_info
      - /predictnav/depth/image_64x64_norm
      - /predictnav/goal
      - /predictnav/start
      - /predictnav/land
      - /move_base_simple/goal
      - /clicked_point
      - /initialpose
      - /predictnav_flight_manager/raw_action
      - /predictnav_flight_manager/ctbr_command
      - /predictnav_flight_manager/status
